// src/components/ui/separator.tsx
import type * as React from 'react'
import * as SeparatorPrimitive from '@radix-ui/react-separator'

import { cn } from '@/lib/utils'

function Separator({
  className,
  orientation = 'horizontal',
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator-root"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        'bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        className,
      )}
      {...props}
    />
  )
}

export { Separator }

// src/components/ui/Separator.vue
<template>
  <hr :class="separatorClass" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { computed, useAttrs } from "vue";

import { cn } from "@/lib/utils";

const props = withDefaults(
  defineProps<{
    orientation?: "horizontal" | "vertical";
  }>(),
  {
    orientation: "horizontal",
  },
);

const attrs = useAttrs();

const separatorClass = computed(() =>
  cn(
    "bg-border shrink-0",
    props.orientation === "horizontal" ? "h-px w-full" : "h-full w-px",
    (attrs.class as string) ?? "",
  ),
);
</script>
